/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ResourceCustomReact: typeof import('~resource/custom/react')['default']
    ResourceCustomReactPng: typeof import('~resource/custom/react/png')['default']
    ResourceCustomVue: typeof import('~resource/custom/vue')['default']
    ResourceCustomVuePng: typeof import('~resource/custom/vue/png')['default']
  }
}
